### ISSUE TITLE
Python bindings/wrapper

### ISSUE THREAD

**Issue by dr-orlovsky** [LNP-BP/rgb-sdk#1]
In the same way as we have them for the other languages

**Comment by UkolovaOlga** [comment]
This task should be reopened @dr-orlovsky, because:

a) you can't find the corresponding Python folder in the `ffi` one [here](https://github.com/LNP-BP/rgb-sdk/tree/master/ffi)
b) you closed this task with [this](https://github.com/LNP-BP/rgb-sdk/commit/0351be1603a35a5525682086763c3cfa96c6a1d0) commit which is old/outdated and not relevant to the current issue.

**Comment by dr-orlovsky** [comment]
Was closed by GitHub mistake since it does not differentiate issues from different projects
